/* global console */
import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFileSync, existsSync } from "node:fs";
import { join } from "node:path";

// Obsidian vault paths that should receive the built plugin automatically.
// Add or remove vaults here as needed.
const VAULT_DEPLOY_PATHS = [
	"D:\\Pauls Obsidian",
	"E:\\CONTENT CREATION\\EXPLORATIONS\\PROJECTS\\AI\\Obsidian Agents and Skills\\Resources\\Obsidian Agents and Skills Vault",
	"E:\\CONTENT CREATION\\EXPLORATIONS\\PROJECTS\\The Ultimate Vault\\Resources\\Obsidian Ultimate Vault",
	"D:\\Obsidian Resources\\Demo Vaults\\Pauls Content",
];

/** Copy main.js, manifest.json, and styles.css to every configured vault. */
function deployToVaults() {
	const files = ["main.js", "manifest.json", "styles.css"];
	for (const vault of VAULT_DEPLOY_PATHS) {
		const pluginDir = join(vault, ".obsidian", "plugins", "obsidianaitools");
		if (!existsSync(join(vault, ".obsidian"))) continue;
		try {
			for (const f of files) {
				if (existsSync(f)) copyFileSync(f, join(pluginDir, f));
			}
			console.log(`  → deployed to ${vault}`);
		} catch (err) {
			console.warn(`  ⚠ could not deploy to ${vault}: ${err.message}`);
		}
	}
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [
		{
			name: "deploy-to-vaults",
			setup(build) {
				build.onEnd((result) => {
					if (result.errors.length === 0) {
						deployToVaults();
					}
				});
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
